### PR TITLE
Update pointers.ipynb

### PR DESCRIPTION
**Pull request by lnperry**
Updated value of some_value to 10 from 42 in documentation

### CODE REVIEW

**Comment by nelson-liu** [comment]
I'm a bit confused...where did the 42 come from? Shouldn't the value be 10?

**Comment by lnperry** [comment]
Yes, I believe so. Maybe it was a typo, the current code says 42 and it should said 10?

**Comment by nelson-liu** [comment]
oops sorry i'm dumb, i read the diff the other way around. Thanks!

**Comment by lnperry** [comment]
We all make silly mistakes, you’re far from dumb! Glad I could help improve the repo that helped me learn more about cython!

**Pull request merged**
